[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
minifb = "0.25"
bimap = "0.6.3"
lazy_static = "1.4.0"
anyhow = "1.0.82"
